import { useState } from 'react'
import { ChevronDown, ChevronRight } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { TaskCard } from './TaskCard'
import type { EmployeeTask } from '@/api/employeeTasks.api'

// Client tasks are generated by the Client Management System's calendar —
// one "Daily Stories — <Month>" parent, plus one task per scheduled Post,
// Reel, and Festive Story. A month can easily produce a dozen-plus of these,
// so they're grouped by content type into collapsible dropdowns rather than
// dumped as one flat grid. The type is read off the task's own title, which
// the CMS always sets to its labelFor() heading ("POST #3", "REEL #1",
// "FESTIVE #2", "Daily Stories — <Month>") — no extra fetch needed to know
// which bucket a task belongs in.
const GROUPS = [
  { key: 'story', label: 'Daily Stories', match: (title: string) => title.startsWith('Daily Stories') },
  { key: 'post', label: 'Posts', match: (title: string) => title.startsWith('POST #') },
  { key: 'reel', label: 'Reels', match: (title: string) => title.startsWith('REEL #') },
  { key: 'festive_story', label: 'Festive Stories', match: (title: string) => title.startsWith('FESTIVE #') },
] as const

function CollapsibleGroup({ label, tasks }: { label: string; tasks: EmployeeTask[] }) {
  const [open, setOpen] = useState(false)
  if (tasks.length === 0) return null

  return (
    <div className="space-y-3">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex items-center gap-2 text-left"
      >
        {open ? <ChevronDown className="size-4 text-muted-foreground" /> : <ChevronRight className="size-4 text-muted-foreground" />}
        <h3 className="text-sm font-extrabold uppercase tracking-wide text-foreground">{label}</h3>
        <Badge variant="outline" className="font-normal">
          {tasks.length}
        </Badge>
      </button>
      {open && (
        <div className="grid gap-4 pl-6 md:grid-cols-2 lg:grid-cols-3">
          {tasks.map((task) => (
            <TaskCard key={task._id} task={task} />
          ))}
        </div>
      )}
    </div>
  )
}

export function ClientTaskGroups({ tasks }: { tasks: EmployeeTask[] }) {
  if (tasks.length === 0) {
    return <p className="text-sm text-muted-foreground">No client related tasks yet.</p>
  }

  const bucketed = GROUPS.map((g) => ({ ...g, tasks: tasks.filter((t) => g.match(t.title)) }))
  const other = tasks.filter((t) => !GROUPS.some((g) => g.match(t.title)))

  return (
    <div className="space-y-5">
      {bucketed.map((g) => (
        <CollapsibleGroup key={g.key} label={g.label} tasks={g.tasks} />
      ))}
      <CollapsibleGroup label="Other" tasks={other} />
    </div>
  )
}
