module.exports = {
  EMPLOYEE_STATUS: { DRAFT: 'draft', ACTIVE: 'active', OFFBOARDED: 'offboarded' },
  UPLOAD_REQUEST_STATUS: {
    PENDING: 'pending',
    PARTIALLY_FULFILLED: 'partially_fulfilled',
    FULFILLED: 'fulfilled',
    EXPIRED: 'expired',
    REVOKED: 'revoked',
  },
  GENERATED_DOCUMENT_STATUS: { COMPLETED: 'completed', FAILED: 'failed' },
  DEFAULT_UPLOAD_REQUEST_EXPIRY_HOURS: 72,
  MAX_UPLOAD_FILE_SIZE_BYTES: 10 * 1024 * 1024, // 10MB
  ALLOWED_UPLOAD_MIME_TYPES: [
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp',
  ],
  ALLOWED_RESUME_MIME_TYPES: [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  ],
  ATTENDANCE_STATUS: {
    PRESENT: 'present',
    ABSENT: 'absent',
    HALF_DAY: 'half_day',
    LEAVE: 'leave',
    WORK_FROM_HOME: 'work_from_home',
    SHORT_DAY: 'short_day',
    EARLY_LEAVE: 'early_leave',
  },
  APPLICANT_STATUS: { APPLIED: 'applied', HIRED: 'hired', REJECTED: 'rejected' },
  CLIENT_STATUS: { LEAD: 'lead', ONBOARDED: 'onboarded', OFFBOARDED: 'offboarded' },
  QUOTATION_STATUS: { DRAFT: 'draft', SHARED: 'shared', SIGNED: 'signed', SUPERSEDED: 'superseded' },
  DEFAULT_QUOTATION_SHARE_EXPIRY_HOURS: 24 * 14,
  USER_ROLES: { ADMIN: 'admin', WORKER: 'worker' },
  TASK_STAGE: {
    PLAN_OF_ACTION: 'plan_of_action',
    POST: 'post',
    SHOOT: 'shoot',
    EDIT: 'edit',
    DESIGN: 'design',
    CALENDAR: 'calendar',
    REPORT: 'report',
    CUSTOM: 'custom',
  },
  TASK_STATUS: { TODO: 'todo', IN_PROGRESS: 'in_progress', BLOCKED: 'blocked', DONE: 'done' },
  TASK_PRIORITY: { LOW: 'low', MEDIUM: 'medium', HIGH: 'high', URGENT: 'urgent' },
};
