module.exports = [
  { key: 'aadhar', label: 'Aadhar Card' },
  { key: 'pan', label: 'PAN Card' },
  { key: 'photo', label: 'Passport Photo' },
  { key: 'passbook_cancelled_cheque', label: 'Passbook / Cancelled Cheque' },
  { key: 'marksheet_10th', label: '10th Marksheet' },
  { key: 'marksheet_12th', label: '12th Marksheet' },
  { key: 'ug_certificate', label: 'UG Certificate' },
  { key: 'pg_certificate', label: 'PG Certificate' },
  { key: 'professional_certificate', label: 'Professional Certificate' },
  { key: 'previous_relieving_letter', label: 'Previous Relieving Letter' },
  { key: 'previous_experience_letter', label: 'Previous Experience Letter' },
  { key: 'previous_salary_slips', label: 'Previous 3 Months Salary Slip' },
  { key: 'other', label: 'Other' },
];
